### ISSUE TITLE
Running with LocalExecutor

### ISSUE THREAD

**Issue by djKooks** [seznam/euphoria#275]
Hello,
I'm first in this project, and trying on sample(with gradle).

I'm going with LocalExecutor, but it keep showing 'cannot find LocalExecutor symbol'.
This is my gradle file.
```
dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    ...
    compile 'cz.seznam.euphoria:euphoria-core:0.7.0'
    compile 'cz.seznam.euphoria:euphoria-local:0.5.0'
    ...
```
It seems it cannot find `euphoria-local 0.5.0` package. Could you let me know correct package name for this?
One more, if I want to use `Spark` or `Flink` executor, is there a guide for that?

Thanks.

**Comment by je-ik** [comment]
Hi, please use the same version for all `euphoria-*` artifacts. The name `LocalExecutor` (and module `euphoria-local`) was first introduced in release `0.8.0-rc1`, so using this version should fix your problem. In versions 0.7.0 ane before, the module was named `euphoria-inmem` and the executor was `InMemExecutor`. Please let us know if this fixed your issue.

Regarding Spark or Flink executor, you can use one of them by adding `euphoria-spark` or `euphoria-flink` artifacts and using `SparkExecutor` or `FlinkExecutor`. There should be some examples in the `examples` module. Documentation is currently a work-in-progress. :-)

**Comment by djKooks** [comment]
@je-ik Thanks for quick response!

One more, can be a dumb question...
when I want to use Spark/Flink Executor, do I have to install Spark/Flink in local first?

**Comment by je-ik** [comment]
@djKooks that depends ... if you want to use spark/flink for tests only, then this should not be needed, because the dependencies will be downloaded from maven central. That means you would instantiate the executor as follows for instance:
```
  SparkExecutor executor = SparkExecutor.newBuilder("test").local().build();
```
That would give you executor that you can use in unit tests. If you want to test your flow on real executor, then you would need a running spark or flink cluster (either local or remote). You then submit your flow using `spark-submit` or `flink` commands.

**Comment by djKooks** [comment]
@je-ik Thanks for help. But I still have some failure with sample...
```
        String inputPath = "input.txt";
        String outputPath = "output.txt";
        DataSource<String> dataSource = new SimpleHadoopTextFileSource(inputPath);
        DataSink<String> dataSink = new SimpleHadoopTextFileSink<>(outputPath);

        // Define a flow, i.e. a chain of transformations
        Flow flow = Flow.create("WordCount");

        Dataset<String> lines = flow.createInput(dataSource);

        Dataset<String> words = FlatMap.named("TOKENIZER")
            .of(lines)
            .using((String line, Context<String> context) -> {
            for (String word : line.split("\\s+")) {
                context.collect(word);
            }
            })
            .output();

        Dataset<Pair<String, Long>> counted = ReduceByKey.named("COUNT")
            .of(words)
            .keyBy(w -> w)
            .valueBy(w -> 1L)
            .combineBy(Sums.ofLongs())
            .output();

        MapElements.named("FORMAT")
            .of(counted)
            .using(p -> p.getFirst() + "\n" + p.getSecond())
            .output()
            .persist(dataSink);

        // Initialize an executor and run the flow (using Apache Flink)
        Executor executor = new LocalExecutor();
        executor.submit(flow).get();
```

...and this catches some error
```
> Task :compileJava
/Users/kwangin/workspace/study/gradleTest/src/main/java/App.java:41: error: cannot find symbol
            .using((String line, Context<String> context) -> {
                                 ^
  symbol:   class Context
  location: class App
/Users/kwangin/workspace/study/gradleTest/src/main/java/App.java:46: error: incompatible types: Dataset<Object> cannot be converted to Dataset<String>
            .output();
                   ^
2 errors
```
Is there something I'm doing wrong?

**Comment by djKooks** [comment]
@je-ik Okay, thanks.
Now I'm trying with sample in project, and it shows other error.
```
Exception in thread "main" java.lang.NoClassDefFoundError: cz/seznam/euphoria/core/client/io/Partition
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1475)
        at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:72)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:498)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:468)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1134)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at java.util.HashSet.writeObject(HashSet.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at cz.seznam.euphoria.core.client.flow.Flow.validateSerializable(Flow.java:208)
        at cz.seznam.euphoria.core.client.flow.Flow.add(Flow.java:170)
        at cz.seznam.euphoria.core.client.flow.Flow.add(Flow.java:147)
        at cz.seznam.euphoria.core.client.operator.FlatMap$OutputBuilder.output(FlatMap.java:172)
        at cz.seznam.euphoria.core.client.operator.FlatMap$EventTimeBuilder.output(FlatMap.java:147)
        at App.buildFlow(App.java:59)
        at App.main(App.java:39)
Caused by: java.lang.ClassNotFoundException: cz.seznam.euphoria.core.client.io.Partition
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 59 more
```

My gradle file is...
```
dependencies {
    ...
    compile 'cz.seznam.euphoria:euphoria-core:0.7.0'
    compile 'cz.seznam.euphoria:euphoria-hadoop:0.5.0'
    compile 'cz.seznam.euphoria:euphoria-local:0.8.0-rc1'
```

Is there something wrong?

**Comment by je-ik** [comment]
You have to have the same version of all `euphoria-*` artifacts, that means ideally
```
dependencies {
    ...
    compile 'cz.seznam.euphoria:euphoria-core:0.8.0-rc1'
    compile 'cz.seznam.euphoria:euphoria-hadoop:0.8.0-rc1'
    compile 'cz.seznam.euphoria:euphoria-local:0.8.0-rc1'
```
These modules are compiled together and have dependencies between them.

**Comment by djKooks** [comment]
@je-ik It seems it is working now. Thanks for help!
