### ISSUE TITLE
Running example with flink

### ISSUE THREAD

**Issue by djKooks** [seznam/euphoria#285]
Hello,
I'm not used to in using flink/gradle so this could be a dummy question. Hope somebody could help.
I'm trying to running example word count like command below:
```
flink run -c cz.seznam.euphoria.examples.wordcount.SimpleWordCount euphoria-examples/build/libs/euphoria-examples-0.8-SNAPSHOT.jar "flink" "input.txt" "output.txt" "2"
```

and it shows like this:
```
java.lang.RuntimeException: Could not look up the main(String[]) method from the class cz.seznam.euphoria.examples.wordcount.SimpleWordCount: cz/seznam/euphoria/core/client/io/DataSource
        at org.apache.flink.client.program.PackagedProgram.hasMainMethod(PackagedProgram.java:498)
        at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:217)
        at org.apache.flink.client.CliFrontend.buildProgram(CliFrontend.java:903)
        at org.apache.flink.client.CliFrontend.run(CliFrontend.java:231)
        at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1086)
        at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1133)
        at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1130)
        at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
        at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1130)
Caused by: java.lang.NoClassDefFoundError: cz/seznam/euphoria/core/client/io/DataSource
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.apache.flink.client.program.PackagedProgram.hasMainMethod(PackagedProgram.java:492)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: cz.seznam.euphoria.core.client.io.DataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more
```
Is there something I'm doing wrong?

**Comment by je-ik** [comment]
You must build shadow jar (jar containing all dependencies) from the examples submodule like this:
```
$ ./gradlew :euphoria-examples:shadowJar
```
That will produce jar in `euphoria-examples/build/libs/euphoria-examples-0.9-SNAPSHOT-all.jar`, which should be runnable. Hope that helps.

**Comment by djKooks** [comment]
@je-ik Thanks,
but I also faced on another issue.

```
Starting execution of program

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:545)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:419)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:381)
        at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:838)
        at org.apache.flink.client.CliFrontend.run(CliFrontend.java:259)
        at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1086)
        at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1133)
        at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1130)
        at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
        at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
        at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1130)
Caused by: java.lang.RuntimeException: java.io.IOException: The given HDFS file URI (hdfs:///tmp/flink/checkpoints) did not describe the HDFS NameNode. The attempt to use a default HDFS configuration, as specified in the 'fs.hdfs.hdfsdefault' or 'fs.hdfs.hdfssite' config parameter failed due to the following problem: Either no default file system was registered, or the provided configuration contains no valid authority component (fs.default.name or fs.defaultFS) describing the (hdfs namenode) host and port.
        at cz.seznam.euphoria.examples.wordcount.SimpleWordCount.main(SimpleWordCount.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:528)
        ... 13 more
Caused by: java.io.IOException: The given HDFS file URI (hdfs:///tmp/flink/checkpoints) did not describe the HDFS NameNode. The attempt to use a default HDFS configuration, as specified in the 'fs.hdfs.hdfsdefault' or 'fs.hdfs.hdfssite' config parameter failed due to the following problem: Either no default file system was registered, or the provided configuration contains no valid authority component (fs.default.name or fs.defaultFS) describing the (hdfs namenode) host and port.
        at org.apache.flink.runtime.fs.hdfs.HadoopFileSystem.initialize(HadoopFileSystem.java:323)
        at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:367)
        at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:389)
        at org.apache.flink.runtime.state.filesystem.FsStateBackend.validateAndNormalizeUri(FsStateBackend.java:372)
        at org.apache.flink.runtime.state.filesystem.FsStateBackend.<init>(FsStateBackend.java:248)
        at org.apache.flink.runtime.state.filesystem.FsStateBackend.<init>(FsStateBackend.java:171)
        at org.apache.flink.contrib.streaming.state.RocksDBStateBackend.<init>(RocksDBStateBackend.java:179)
        at org.apache.flink.contrib.streaming.state.RocksDBStateBackend.<init>(RocksDBStateBackend.java:129)
        at cz.seznam.euphoria.examples.Executors$FlinkFactory.create(Executors.java:78)
        at cz.seznam.euphoria.examples.Executors.createExecutor(Executors.java:133)
        at cz.seznam.euphoria.examples.wordcount.SimpleWordCount.main(SimpleWordCount.java:134)
        ... 18 more
```

**Comment by je-ik** [comment]
@djKooks How does your environment look like? It seems you don't have hadoop configured (default filesystem is missing). You should either get your `hdfs-site.xml` and `core-site.xml` to flink's classpath, or you could patch `euphoria-examples/src/main/java/cz/seznam/euphoria/examples/Executors.java` to query your namenode from command line. PRs welcome! :-)

**Comment by djKooks** [comment]
@je-ik Yes, hadoop is not installed in local.
Is there a guide to look on that?

**Comment by djKooks** [comment]
@je-ik thanks.
As you said, I fixed path to `file:///home/xxx/test"` but it shows like
```
Call From kwangin-ui-MacBook-Pro.local/192.168.2.1 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
        at org.apache.hadoop.ipc.Client.call(Client.java:1479)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy11.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2108)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
        at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
        at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:57)
        at org.apache.hadoop.fs.Globber.glob(Globber.java:252)
        at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1676)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:294)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:265)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:387)
        at cz.seznam.euphoria.hadoop.input.HadoopSource.lambda$doSplit$1(HadoopSource.java:68)
        at cz.seznam.euphoria.core.util.ExceptionUtils.unchecked(ExceptionUtils.java:35)
        ... 23 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)
        at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:614)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:712)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        at org.apache.hadoop.ipc.Client.call(Client.java:1451)
        ... 47 more
```
Do I have to run hadoop for this?

Thanks.

**Comment by je-ik** [comment]
That looks like you are trying to read input files from HDFS. You can change this to `file:` scheme also (both for input and output). That should be specified on the command line.

**Comment by djKooks** [comment]
@je-ik thanks.
As you mentioned I tested again with `flink run -c cz.seznam.euphoria.examples.wordcount.SimpleWordCount build/libs/euphoria-examples-0.8-SNAPSHOT-all.jar "flink" "file:///Users/kwangin/workspace/euphoria/input.txt" "file:///Users/kwangin/workspace/euphoria/input.txt" "2"`

and this seems connection is success, but caused error while reading.

```
...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/kwangin/software/flink-1.4.2/lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/Cellar/hadoop/2.7.3/libexec/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Cluster configuration: Standalone cluster with JobManager at localhost/127.0.0.1:6123
Using address localhost:6123 to connect to JobManager.
JobManager web interface address http://localhost:8081
Starting execution of program
2018-05-15 19:52:31,523 INFO  org.apache.hadoop.mapreduce.lib.input.FileInputFormat         - Total input paths to process : 1
Submitting job with JobID: dc9734de828c284c845c732d396599cb. Waiting for job completion.
Connected to JobManager at Actor[akka.tcp://flink@localhost:6123/user/jobmanager#-239931855] with leader session id 00000000-0000-0000-0000-000000000000.
05/15/2018 19:52:34     Job execution switched to status RUNNING.
05/15/2018 19:52:34     CHAIN DataSource (at createInput(ExecutionEnvironment.java:547) (cz.seznam.euphoria.flink.batch.io.DataSourceWrapper)) -> FlatMap (TOKENIZER) -> FlatMap (REDUCE::map-input) -> Map (Key Extractor) -> Combine(REDUCE::reduce)(1/1) switched to SCHEDULED 
05/15/2018 19:52:34     CHAIN DataSource (at createInput(ExecutionEnvironment.java:547) (cz.seznam.euphoria.flink.batch.io.DataSourceWrapper)) -> FlatMap (TOKENIZER) -> FlatMap (REDUCE::map-input) -> Map (Key Extractor) -> Combine(REDUCE::reduce)(1/1) switched to DEPLOYING 
05/15/2018 19:52:35     CHAIN DataSource (at createInput(ExecutionEnvironment.java:547) (cz.seznam.euphoria.flink.batch.io.DataSourceWrapper)) -> FlatMap (TOKENIZER) -> FlatMap (REDUCE::map-input) -> Map (Key Extractor) -> Combine(REDUCE::reduce)(1/1) switched to RUNNING 
05/15/2018 19:52:35     CHAIN Reduce (REDUCE::reduce) -> FlatMap (FORMAT)(1/1) switched to SCHEDULED 
05/15/2018 19:52:35     CHAIN Reduce (REDUCE::reduce) -> FlatMap (FORMAT)(1/1) switched to DEPLOYING 
05/15/2018 19:52:35     CHAIN Reduce (REDUCE::reduce) -> FlatMap (FORMAT)(1/1) switched to RUNNING 
05/15/2018 19:52:35     CHAIN DataSource (at createInput(ExecutionEnvironment.java:547) (cz.seznam.euphoria.flink.batch.io.DataSourceWrapper)) -> FlatMap (TOKENIZER) -> FlatMap (REDUCE::map-input) -> Map (Key Extractor) -> Combine(REDUCE::reduce)(1/1) switched to FINISHED 
05/15/2018 19:52:35     DataSink (cz.seznam.euphoria.flink.batch.io.DataSinkWrapper@780e1116)(1/1) switched to SCHEDULED 
05/15/2018 19:52:35     DataSink (cz.seznam.euphoria.flink.batch.io.DataSinkWrapper@780e1116)(1/1) switched to DEPLOYING 
05/15/2018 19:52:35     DataSink (cz.seznam.euphoria.flink.batch.io.DataSinkWrapper@780e1116)(1/1) switched to RUNNING 
05/15/2018 19:52:35     CHAIN Reduce (REDUCE::reduce) -> FlatMap (FORMAT)(1/1) switched to FINISHED 
05/15/2018 19:52:36     DataSink (cz.seznam.euphoria.flink.batch.io.DataSinkWrapper@780e1116)(1/1) switched to FAILED 
java.lang.RuntimeException: org.apache.hadoop.fs.ParentNotDirectoryException: Parent path is not a directory: file:/Users/kwangin/workspace/euphoria/input.txt
        at cz.seznam.euphoria.hadoop.output.HadoopSink.openWriter(HadoopSink.java:85)
        at cz.seznam.euphoria.hadoop.output.SimpleHadoopTextFileSink.openWriter(SimpleHadoopTextFileSink.java:93)
        at cz.seznam.euphoria.flink.batch.io.DataSinkWrapper.open(DataSinkWrapper.java:44)
        at org.apache.flink.runtime.operators.DataSinkTask.invoke(DataSinkTask.java:178)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.fs.ParentNotDirectoryException: Parent path is not a directory: file:/Users/kwangin/workspace/euphoria/input.txt
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:523)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:504)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:531)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:504)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:531)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:504)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:531)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:504)
        at org.apache.hadoop.fs.ChecksumFileSystem.mkdirs(ChecksumFileSystem.java:694)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:453)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.hadoop.mapreduce.lib.output.TextOutputFormat.getRecordWriter(TextOutputFormat.java:132)
        at cz.seznam.euphoria.hadoop.output.HadoopSink.openWriter(HadoopSink.java:81)
        ... 5 more
...
```
Could you find something?

**Comment by je-ik** [comment]
You must specify empty output directory, you have the same output file as input. I.e.:
```
flink run -c cz.seznam.euphoria.examples.wordcount.SimpleWordCount build/libs/euphoria-examples-0.8-SNAPSHOT-all.jar "flink" "file:///Users/kwangin/workspace/euphoria/input.txt" "file:///Users/kwangin/workspace/euphoria/output" "2"
```

**Comment by djKooks** [comment]
@je-ik now it works. Thanks!

**Comment by Moussa-Guemdani** [comment]
Hello,

I have a similar issue, and I think you could help me with this

I get this error when ever I submit my flink job (same for kafka source and sink)

The program finished with the following exception:

java.lang.RuntimeException: Could not look up the main(String[]) method from the class com.moussa.cnam.cedric.fr.ProcessingAppPipeline: org/apache/flink/connector/kafka/source/KafkaSource
	at org.apache.flink.client.program.PackagedProgram.hasMainMethod(PackagedProgram.java:315)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:161)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65)
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691)
	at org.apache.flink.client.cli.CliFrontend.buildProgram(CliFrontend.java:882)
	at org.apache.flink.client.cli.CliFrontend.getPackagedProgram(CliFrontend.java:265)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:239)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1087)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1165)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1165)
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/connector/kafka/source/KafkaSource
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at org.apache.flink.client.program.PackagedProgram.hasMainMethod(PackagedProgram.java:307)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.kafka.source.KafkaSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:67)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)

**Comment by je-ik** [comment]
Hi @Moussa-Guemdani,
this repository is not maintained anymore. Most of its codebase has been migrated to https://github.com/apache/beam under Euphoria extension. I would recommend using Apache Beam directly, though.

**Comment by Moussa-Guemdani** [comment]
Thank you very much sir!
